# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motor_control.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='motor_control.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13motor_control.proto\"U\n\x17ReqMotorServiceJoystick\x12\x14\n\x0cvector_angle\x18\x01 \x01(\x01\x12\x15\n\rvector_length\x18\x02 \x01(\x01\x12\r\n\x05speed\x18\x03 \x01(\x01\"_\n!ReqMotorServiceJoystickFixedAngle\x12\x14\n\x0cvector_angle\x18\x01 \x01(\x01\x12\x15\n\rvector_length\x18\x02 \x01(\x01\x12\r\n\x05speed\x18\x03 \x01(\x01\"\x1d\n\x1bReqMotorServiceJoystickStop\"l\n\x0bReqMotorRun\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05speed\x18\x02 \x01(\x01\x12\x11\n\tdirection\x18\x03 \x01(\x08\x12\x15\n\rspeed_ramping\x18\x04 \x01(\x05\x12\x18\n\x10resolution_level\x18\x05 \x01(\x05\"q\n\rReqMotorRunTo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0c\x65nd_position\x18\x02 \x01(\x01\x12\r\n\x05speed\x18\x03 \x01(\x01\x12\x15\n\rspeed_ramping\x18\x04 \x01(\x05\x12\x18\n\x10resolution_level\x18\x05 \x01(\x05\"\x1a\n\x0cReqMotorStop\x12\n\n\x02id\x18\x01 \x01(\x05\".\n\rReqMotorReset\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tdirection\x18\x02 \x01(\x08\"0\n\x13ReqMotorChangeSpeed\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05speed\x18\x02 \x01(\x01\"8\n\x17ReqMotorChangeDirection\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tdirection\x18\x02 \x01(\x08\"$\n\x08ResMotor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\">\n\x10ResMotorPosition\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x10\n\x08position\x18\x03 \x01(\x01\",\n\x14ReqDualCameraLinkage\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x62\x06proto3'
)




_REQMOTORSERVICEJOYSTICK = _descriptor.Descriptor(
  name='ReqMotorServiceJoystick',
  full_name='ReqMotorServiceJoystick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector_angle', full_name='ReqMotorServiceJoystick.vector_angle', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vector_length', full_name='ReqMotorServiceJoystick.vector_length', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='ReqMotorServiceJoystick.speed', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=108,
)


_REQMOTORSERVICEJOYSTICKFIXEDANGLE = _descriptor.Descriptor(
  name='ReqMotorServiceJoystickFixedAngle',
  full_name='ReqMotorServiceJoystickFixedAngle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector_angle', full_name='ReqMotorServiceJoystickFixedAngle.vector_angle', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vector_length', full_name='ReqMotorServiceJoystickFixedAngle.vector_length', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='ReqMotorServiceJoystickFixedAngle.speed', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=205,
)


_REQMOTORSERVICEJOYSTICKSTOP = _descriptor.Descriptor(
  name='ReqMotorServiceJoystickStop',
  full_name='ReqMotorServiceJoystickStop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=236,
)


_REQMOTORRUN = _descriptor.Descriptor(
  name='ReqMotorRun',
  full_name='ReqMotorRun',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ReqMotorRun.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='ReqMotorRun.speed', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='direction', full_name='ReqMotorRun.direction', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed_ramping', full_name='ReqMotorRun.speed_ramping', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resolution_level', full_name='ReqMotorRun.resolution_level', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=346,
)


_REQMOTORRUNTO = _descriptor.Descriptor(
  name='ReqMotorRunTo',
  full_name='ReqMotorRunTo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ReqMotorRunTo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_position', full_name='ReqMotorRunTo.end_position', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='ReqMotorRunTo.speed', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed_ramping', full_name='ReqMotorRunTo.speed_ramping', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resolution_level', full_name='ReqMotorRunTo.resolution_level', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=461,
)


_REQMOTORSTOP = _descriptor.Descriptor(
  name='ReqMotorStop',
  full_name='ReqMotorStop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ReqMotorStop.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=489,
)


_REQMOTORRESET = _descriptor.Descriptor(
  name='ReqMotorReset',
  full_name='ReqMotorReset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ReqMotorReset.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='direction', full_name='ReqMotorReset.direction', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=537,
)


_REQMOTORCHANGESPEED = _descriptor.Descriptor(
  name='ReqMotorChangeSpeed',
  full_name='ReqMotorChangeSpeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ReqMotorChangeSpeed.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='ReqMotorChangeSpeed.speed', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=587,
)


_REQMOTORCHANGEDIRECTION = _descriptor.Descriptor(
  name='ReqMotorChangeDirection',
  full_name='ReqMotorChangeDirection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ReqMotorChangeDirection.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='direction', full_name='ReqMotorChangeDirection.direction', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=589,
  serialized_end=645,
)


_RESMOTOR = _descriptor.Descriptor(
  name='ResMotor',
  full_name='ResMotor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ResMotor.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='ResMotor.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=647,
  serialized_end=683,
)


_RESMOTORPOSITION = _descriptor.Descriptor(
  name='ResMotorPosition',
  full_name='ResMotorPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ResMotorPosition.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='ResMotorPosition.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='ResMotorPosition.position', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=747,
)


_REQDUALCAMERALINKAGE = _descriptor.Descriptor(
  name='ReqDualCameraLinkage',
  full_name='ReqDualCameraLinkage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ReqDualCameraLinkage.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='ReqDualCameraLinkage.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=749,
  serialized_end=793,
)

DESCRIPTOR.message_types_by_name['ReqMotorServiceJoystick'] = _REQMOTORSERVICEJOYSTICK
DESCRIPTOR.message_types_by_name['ReqMotorServiceJoystickFixedAngle'] = _REQMOTORSERVICEJOYSTICKFIXEDANGLE
DESCRIPTOR.message_types_by_name['ReqMotorServiceJoystickStop'] = _REQMOTORSERVICEJOYSTICKSTOP
DESCRIPTOR.message_types_by_name['ReqMotorRun'] = _REQMOTORRUN
DESCRIPTOR.message_types_by_name['ReqMotorRunTo'] = _REQMOTORRUNTO
DESCRIPTOR.message_types_by_name['ReqMotorStop'] = _REQMOTORSTOP
DESCRIPTOR.message_types_by_name['ReqMotorReset'] = _REQMOTORRESET
DESCRIPTOR.message_types_by_name['ReqMotorChangeSpeed'] = _REQMOTORCHANGESPEED
DESCRIPTOR.message_types_by_name['ReqMotorChangeDirection'] = _REQMOTORCHANGEDIRECTION
DESCRIPTOR.message_types_by_name['ResMotor'] = _RESMOTOR
DESCRIPTOR.message_types_by_name['ResMotorPosition'] = _RESMOTORPOSITION
DESCRIPTOR.message_types_by_name['ReqDualCameraLinkage'] = _REQDUALCAMERALINKAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqMotorServiceJoystick = _reflection.GeneratedProtocolMessageType('ReqMotorServiceJoystick', (_message.Message,), {
  'DESCRIPTOR' : _REQMOTORSERVICEJOYSTICK,
  '__module__' : 'motor_control_pb2'
  # @@protoc_insertion_point(class_scope:ReqMotorServiceJoystick)
  })
_sym_db.RegisterMessage(ReqMotorServiceJoystick)

ReqMotorServiceJoystickFixedAngle = _reflection.GeneratedProtocolMessageType('ReqMotorServiceJoystickFixedAngle', (_message.Message,), {
  'DESCRIPTOR' : _REQMOTORSERVICEJOYSTICKFIXEDANGLE,
  '__module__' : 'motor_control_pb2'
  # @@protoc_insertion_point(class_scope:ReqMotorServiceJoystickFixedAngle)
  })
_sym_db.RegisterMessage(ReqMotorServiceJoystickFixedAngle)

ReqMotorServiceJoystickStop = _reflection.GeneratedProtocolMessageType('ReqMotorServiceJoystickStop', (_message.Message,), {
  'DESCRIPTOR' : _REQMOTORSERVICEJOYSTICKSTOP,
  '__module__' : 'motor_control_pb2'
  # @@protoc_insertion_point(class_scope:ReqMotorServiceJoystickStop)
  })
_sym_db.RegisterMessage(ReqMotorServiceJoystickStop)

ReqMotorRun = _reflection.GeneratedProtocolMessageType('ReqMotorRun', (_message.Message,), {
  'DESCRIPTOR' : _REQMOTORRUN,
  '__module__' : 'motor_control_pb2'
  # @@protoc_insertion_point(class_scope:ReqMotorRun)
  })
_sym_db.RegisterMessage(ReqMotorRun)

ReqMotorRunTo = _reflection.GeneratedProtocolMessageType('ReqMotorRunTo', (_message.Message,), {
  'DESCRIPTOR' : _REQMOTORRUNTO,
  '__module__' : 'motor_control_pb2'
  # @@protoc_insertion_point(class_scope:ReqMotorRunTo)
  })
_sym_db.RegisterMessage(ReqMotorRunTo)

ReqMotorStop = _reflection.GeneratedProtocolMessageType('ReqMotorStop', (_message.Message,), {
  'DESCRIPTOR' : _REQMOTORSTOP,
  '__module__' : 'motor_control_pb2'
  # @@protoc_insertion_point(class_scope:ReqMotorStop)
  })
_sym_db.RegisterMessage(ReqMotorStop)

ReqMotorReset = _reflection.GeneratedProtocolMessageType('ReqMotorReset', (_message.Message,), {
  'DESCRIPTOR' : _REQMOTORRESET,
  '__module__' : 'motor_control_pb2'
  # @@protoc_insertion_point(class_scope:ReqMotorReset)
  })
_sym_db.RegisterMessage(ReqMotorReset)

ReqMotorChangeSpeed = _reflection.GeneratedProtocolMessageType('ReqMotorChangeSpeed', (_message.Message,), {
  'DESCRIPTOR' : _REQMOTORCHANGESPEED,
  '__module__' : 'motor_control_pb2'
  # @@protoc_insertion_point(class_scope:ReqMotorChangeSpeed)
  })
_sym_db.RegisterMessage(ReqMotorChangeSpeed)

ReqMotorChangeDirection = _reflection.GeneratedProtocolMessageType('ReqMotorChangeDirection', (_message.Message,), {
  'DESCRIPTOR' : _REQMOTORCHANGEDIRECTION,
  '__module__' : 'motor_control_pb2'
  # @@protoc_insertion_point(class_scope:ReqMotorChangeDirection)
  })
_sym_db.RegisterMessage(ReqMotorChangeDirection)

ResMotor = _reflection.GeneratedProtocolMessageType('ResMotor', (_message.Message,), {
  'DESCRIPTOR' : _RESMOTOR,
  '__module__' : 'motor_control_pb2'
  # @@protoc_insertion_point(class_scope:ResMotor)
  })
_sym_db.RegisterMessage(ResMotor)

ResMotorPosition = _reflection.GeneratedProtocolMessageType('ResMotorPosition', (_message.Message,), {
  'DESCRIPTOR' : _RESMOTORPOSITION,
  '__module__' : 'motor_control_pb2'
  # @@protoc_insertion_point(class_scope:ResMotorPosition)
  })
_sym_db.RegisterMessage(ResMotorPosition)

ReqDualCameraLinkage = _reflection.GeneratedProtocolMessageType('ReqDualCameraLinkage', (_message.Message,), {
  'DESCRIPTOR' : _REQDUALCAMERALINKAGE,
  '__module__' : 'motor_control_pb2'
  # @@protoc_insertion_point(class_scope:ReqDualCameraLinkage)
  })
_sym_db.RegisterMessage(ReqDualCameraLinkage)


# @@protoc_insertion_point(module_scope)
