# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: panorama.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='panorama.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0epanorama.proto\"4\n\x16ReqStartPanoramaByGrid\x12\x0c\n\x04rows\x18\x01 \x01(\r\x12\x0c\n\x04\x63ols\x18\x02 \x01(\r\"F\n\x1cReqStartPanoramaByEulerRange\x12\x11\n\tyaw_range\x18\x01 \x01(\x02\x12\x13\n\x0bpitch_range\x18\x02 \x01(\x02\"\x11\n\x0fReqStopPanoramab\x06proto3'
)




_REQSTARTPANORAMABYGRID = _descriptor.Descriptor(
  name='ReqStartPanoramaByGrid',
  full_name='ReqStartPanoramaByGrid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='ReqStartPanoramaByGrid.rows', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cols', full_name='ReqStartPanoramaByGrid.cols', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=70,
)


_REQSTARTPANORAMABYEULERRANGE = _descriptor.Descriptor(
  name='ReqStartPanoramaByEulerRange',
  full_name='ReqStartPanoramaByEulerRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='yaw_range', full_name='ReqStartPanoramaByEulerRange.yaw_range', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pitch_range', full_name='ReqStartPanoramaByEulerRange.pitch_range', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=142,
)


_REQSTOPPANORAMA = _descriptor.Descriptor(
  name='ReqStopPanorama',
  full_name='ReqStopPanorama',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['ReqStartPanoramaByGrid'] = _REQSTARTPANORAMABYGRID
DESCRIPTOR.message_types_by_name['ReqStartPanoramaByEulerRange'] = _REQSTARTPANORAMABYEULERRANGE
DESCRIPTOR.message_types_by_name['ReqStopPanorama'] = _REQSTOPPANORAMA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqStartPanoramaByGrid = _reflection.GeneratedProtocolMessageType('ReqStartPanoramaByGrid', (_message.Message,), {
  'DESCRIPTOR' : _REQSTARTPANORAMABYGRID,
  '__module__' : 'panorama_pb2'
  # @@protoc_insertion_point(class_scope:ReqStartPanoramaByGrid)
  })
_sym_db.RegisterMessage(ReqStartPanoramaByGrid)

ReqStartPanoramaByEulerRange = _reflection.GeneratedProtocolMessageType('ReqStartPanoramaByEulerRange', (_message.Message,), {
  'DESCRIPTOR' : _REQSTARTPANORAMABYEULERRANGE,
  '__module__' : 'panorama_pb2'
  # @@protoc_insertion_point(class_scope:ReqStartPanoramaByEulerRange)
  })
_sym_db.RegisterMessage(ReqStartPanoramaByEulerRange)

ReqStopPanorama = _reflection.GeneratedProtocolMessageType('ReqStopPanorama', (_message.Message,), {
  'DESCRIPTOR' : _REQSTOPPANORAMA,
  '__module__' : 'panorama_pb2'
  # @@protoc_insertion_point(class_scope:ReqStopPanorama)
  })
_sym_db.RegisterMessage(ReqStopPanorama)


# @@protoc_insertion_point(module_scope)
